### ISSUE TITLE
failed unit tests

### ISSUE THREAD

**Issue by timmolter** [zscott/MultiBitExchange#12]
```
testFriendlyFormatDefaultLocale(org.multibit.common.DateUtilsTest): expected:<[Saturday, January 0]1> but was:<[Friday, December 3]1>
testFriendlyFormatFrenchLocale(org.multibit.common.DateUtilsTest): expected:<[samedi, janvier 0]1> but was:<[vendredi, décembre 3]1>
```

**Comment by zscott** [comment]
I have seen one these tests fail previously, but currently they pass on all of my available environments. I have attempted to fix, but can't verify the fix. 

Can you share your environment details with me? JVM Version, OS, Local, etc.

Thanks,

Zach

**Comment by timmolter** [comment]
JVM is 1.7, Mac OSX, CET, Germany.

For testing dates you may consider something line I did here recently:

line 110: https://github.com/Kyje/XChange/blob/70a4997f630f38b0c78244615be7e1a27d3774ae/xchange-mtgox/src/test/java/com/xeiam/xchange/mtgox/v1/service/MtGoxAdapterTest.java

perhaps that will make you tests more robust across different build servers and dev computers.
